### ISSUE TITLE
Blbne hreflang

### ISSUE THREAD

**Issue by vasimi** [MozillaCZ/frontierline-mozillacz#7]
Na https://www.mozilla.cz/zpravicky/mozilla-ma-nove-logo/ blbe hreflang, není malý a není zarovnaný nahoru, vypadá jako normální text.

**Comment by MikkCZ** [comment]
Firefox s tím nemá problém, je to bug ve WebKitu a Blinku. DevTools v Chromiu mi dokonce tvrdí, že velikost toho textu skutečně je 0.5em a spočítají mi to na pixely, ale nezobrazí se to tak.

A když jsem to tak proklikával, vypadá to na nějakou kolizi s pravidlem z _content-full.scss.
```css
.single .post .entry-content > p:first-child:not(.disclaimer):first-line,
.single .post .entry-content > .disclaimer:first-child + p:first-line,
.single .page .entry-content > p:first-child:not(.disclaimer):first-line,
.single .page .entry-content > .disclaimer:first-child + p:first-line,
.page .post .entry-content > p:first-child:not(.disclaimer):first-line,
.page .post .entry-content > .disclaimer:first-child + p:first-line,
.page .page .entry-content > p:first-child:not(.disclaimer):first-line,
.page .page .entry-content > .disclaimer:first-child + p:first-line {
    font-size: 24px;
    font-size: 1.3333333333rem;
}

.single .post .entry-content > p:first-child:not(.disclaimer):first-line,
.single .post .entry-content > .disclaimer:first-child + p:first-line,
.single .page .entry-content > p:first-child:not(.disclaimer):first-line,
.single .page .entry-content > .disclaimer:first-child + p:first-line,
.page .post .entry-content > p:first-child:not(.disclaimer):first-line,
.page .post .entry-content > .disclaimer:first-child + p:first-line,
.page .page .entry-content > p:first-child:not(.disclaimer):first-line,
.page .page .entry-content > .disclaimer:first-child + p:first-line {
    font-size: 18px;
    font-size: 1rem;
}
```
